#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Drocal\Command\PlatformDumpCommand;

$application = new Application();

// ... register commands
$application->add(new PlatformDumpCommand());

$application->run();
