#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Drocal\Command\D7LocalCommand;
use Drocal\Command\PlatformshDumpCommand;

$application = new Application();

// ... register commands
$application->add(new D7LocalCommand());
$application->add(new PlatformshDumpCommand());

$application->run();
